spring:
  application:
    name: oauth2-example
#  security:
#    oauth2:
#      client:
#        registration:#          authz-server:
#            client-id: SampleClientId
#            client-secret: secret
#        provider:
#          authz-server:
#            token-uri: http://localhost:8081/auth/oauth2/v1/token
#            authorization-uri: http://localhost:8081/auth/oauth2/v1/authorize
#            user-info-uri: http://localhost:8081/auth/oauth2/v1/userinfo
security:
  oauth2:
    client:
      clientId: SampleClientId
      clientSecret: secret
      accessTokenUri: http://localhost:8081/auth/oauth/token
      userAuthorizationUri: http://localhost:8081/auth/oauth/authorize
    resource:
      userInfoUri: http://localhost:8081/auth/user/me
#security:
#  oauth2:
#    client:
#      clientId: bd1c0a783ccdd1c9b9e4
#      clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
#      accessTokenUri: https://github.com/login/oauth/access_token
#      userAuthorizationUri: https://github.com/login/oauth/authorize
#      clientAuthenticationScheme: form
#    resource:
#      userInfoUri: https://api.github.com/user